name: Destroy Terraform Resources

on:
  #schedule:
  #  - cron: "0 17 * * *"
  workflow_dispatch:
  
jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6-beta

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Destroy Resources
        run: |
          terraform init
          terraform destroy --auto-approve
          
